export const GENERATION_ERROR_CODES = Object.freeze({
  NANO_BANANA_API_KEY_NOT_CONFIGURED: "NANO_BANANA_API_KEY_NOT_CONFIGURED",
  NANO_BANANA_BASE_URL_NOT_CONFIGURED: "NANO_BANANA_BASE_URL_NOT_CONFIGURED",
  NANO_BANANA_MODEL_NOT_CONFIGURED: "NANO_BANANA_MODEL_NOT_CONFIGURED",
  PROVIDER_CONFIGURATION_INCOMPLETE: "PROVIDER_CONFIGURATION_INCOMPLETE",
  PROVIDER_PROTOCOL_NOT_CONFIGURED: "PROVIDER_PROTOCOL_NOT_CONFIGURED",
  PROVIDER_AUTH_ERROR: "PROVIDER_AUTH_ERROR",
  PROVIDER_RATE_LIMIT: "PROVIDER_RATE_LIMIT",
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_BAD_RESPONSE: "PROVIDER_BAD_RESPONSE",
  PROVIDER_GENERATION_FAILED: "PROVIDER_GENERATION_FAILED",
  ASSET_UPLOAD_FAILED: "ASSET_UPLOAD_FAILED",
  OUTPUT_NOT_FOUND: "OUTPUT_NOT_FOUND",
  INVALID_GENERATION_REQUEST: "INVALID_GENERATION_REQUEST",
  ASSET_RESOLUTION_MISSING: "ASSET_RESOLUTION_MISSING",
  ASSET_ROLE_MISMATCH: "ASSET_ROLE_MISMATCH",
  REFERENCE_BINDING_MISSING: "REFERENCE_BINDING_MISSING",
  IDENTITY_BINDING_MISSING: "IDENTITY_BINDING_MISSING",
  INVALID_GENERATION_RESULT: "INVALID_GENERATION_RESULT",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED"
});

export class GenerationError extends Error {
  constructor(code, message, details = {}, options = {}) {
    super(message, options);
    this.name = "GenerationError";
    this.code = code;
    this.details = details;
    this.retryable = options.retryable ?? false;
  }
}

export class NanoBananaConfigError extends GenerationError {
  constructor(code, details = {}) {
    super(code, "Nano Banana provider ainda não configurado. Substitua SUBSTITUA_PELA_API, SUBSTITUA_PELA_URL_DA_API e SUBSTITUA_PELO_MODELO pelas credenciais/configuração reais no arquivo .env.", { ...details, provider_configured: false });
    this.name = "NanoBananaConfigError";
  }
}
