export const COMPILER_ERROR_CODES = Object.freeze({
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  INVALID_PROFILE: "INVALID_PROFILE",
  PROFILE_TARGET_MISMATCH: "PROFILE_TARGET_MISMATCH",
  INVALID_COMPILER_INPUT: "INVALID_COMPILER_INPUT",
  FINAL_FRAME_NOT_COMPILABLE: "FINAL_FRAME_NOT_COMPILABLE",
  FINAL_FRAME_REF_MISMATCH: "FINAL_FRAME_REF_MISMATCH",
  MISSING_REQUIRED_ASSET: "MISSING_REQUIRED_ASSET",
  INVALID_BINDING: "INVALID_BINDING",
  CAPABILITY_BLOCK: "CAPABILITY_BLOCK",
  HARD_LOCK_CONFLICT: "HARD_LOCK_CONFLICT",
  REFERENCE_DILUTION: "REFERENCE_DILUTION",
  COMPILER_LOSS_DETECTED: "COMPILER_LOSS_DETECTED",
  INVALID_COMPILED_REQUEST: "INVALID_COMPILED_REQUEST"
});

export class CompilerError extends Error {
  constructor(code, message, details = {}) {
    super(message);
    this.name = "CompilerError";
    this.code = code;
    this.details = details;
  }
}